baseURL = "http://amrhub.ru"
languageCode = "ru-RU"
defaultContentLanguage = "ru"
title = "AMRhub"
theme = "landing-page-hugo-master"
googleAnalytics = "UA-85066436-4"
copyright = "IACMAC"
publishDir = "../docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.ru]
title = "AMRhub"
description = "Вас приветствует сайт AMRhub — виртуальная точка входа для целой экосистемы уникальных веб-продуктов, созданных специалистами НИИ антимикробной химиотерапии (НИИАХ) ФГБОУ ВО «Смоленский государственный медицинский университет» Министерства здравоохранения Российской Федерации и Межрегиональной ассоциации по клинической микробиологии и антимикробной химиотерапии (МАКМАХ)."
socialText = "Давайте дружить!"
goToText = "Перейти на"
inProgressText = "в разработке"
weight = 1
languageName = "Русский"
keywords = "AMRhub, AMRmap, AMRbook, AMRguide, IACMAC, AMRseq, antimicrobials, antibiotics, SNP typing, SNPTAB, SNPTPA, МАКМАХ, антибиотики, антибиотикорезистентность"

[Languages.en]
title = "AMRhub"
description = "Welcome to AMRhub — a virtual entry point to the whole ecosystem of The Interregional Association for Clinical Microbiology and Antimicrobial Chemotherapy (IACMAC) web products."
socialText = "Stay In Touch:"
goToText = "Go to"
inProgressText = "is in progress"
weight = 2
languageName = "English"
keywords = "AMRhub, AMRmap, AMRbook, AMRguide, IACMAC, AMRseq, antimicrobials, antibiotics, SNP typing, SNPTAB, SNPTPA, МАКМАХ, antibiotics, antimicrobialresistance"


[params]
    custom_css = ["/css/local.css"]

[[params.social]]
    title = "email"
    icon = "envelope-o"
    url = "mailto:andrey.avramenko@antibiotic.ru"
[[params.social]]
    title = "Web"
    icon = "globe"
    url = "http://www.iacmac.ru/iacmac/"
[[params.social]]
    title = "twitter"
    icon = "twitter"
    url = "https://twitter.com/iacmac1997"
[[params.social]]
    title = "facebook"
    icon = "facebook"
    url = "https://www.facebook.com/iacmac/"
[[params.social]]
    title = "instagram"
    icon = "instagram"
    url = "https://www.instagram.com/iacmac1997/"
[[params.social]]
    title = "Vkontakte"
    icon = "vk"
    url = "https://vk.com/iacmac"
[[params.social]]
    title = "Telegram"
    icon = "telegram"
    url = "https://t.me/iacmac"


[[params.services]]
    title = "AMRmap"
    icon = "map"
    url = "http://amrmap.ru"
[[params.services]]
    title = "AMRpaint"
    icon = "paint-brush"
    url = "http://paint.amrmap.ru/"
[[params.services]]
    title = "SNPT"
    icon = "pie-chart"
    url = "http://snpt.antibiotic.ru"
[[params.services]]
    title = "CityMap"
    icon = "building"
    url = "https://iacmac-web-tools.github.io/CityMap/"


[[params.links.ru]]
    title = "AMRmap"
    icon = "map"
    url = "http://amrmap.ru"
[[params.links.ru]]
    title = "AMRpaint"
    icon = "paint-brush"
    url = "http://paint.amrmap.ru/"
[[params.links.ru]]
    title = "SNPT"
    icon = "pie-chart"
    url = "http://snpt.antibiotic.ru"
[[params.links.ru]]
    title = "CityMap"
    icon = "building"
    url = "https://iacmac-web-tools.github.io/CityMap/"
    
[[params.links.en]]
    title = "AMRmap"
    icon = "map"
    url = "http://amrmap.net"
[[params.links.en]]
    title = "AMRpaint"
    icon = "paint-brush"
    url = "http://paint.amrmap.ru/"
[[params.links.en]]
    title = "SNPT"
    icon = "pie-chart"
    url = "http://snpt.antibiotic.ru"
[[params.links.en]]
    title = "CityMap"
    icon = "building"
    url = "https://iacmac-web-tools.github.io/CityMap/"

